### ISSUE TITLE
请问有没有数据集的文件呢

### ISSUE THREAD

**Issue by subingquan123** [TommyGong08/LSTM_Trajectory_Prediction#2]

**Comment by GongHailong08** [comment]
你好，data_single_vehicle.csv里面是数据集的文件。需要更多数据的话可以去看一下NGSIM数据集。

**Comment by subingquan123** [comment]
感谢回复，你在data.py文件中用到的文件不是data_single_vehicle.csv，我想问的是关于data.py里面使用到的那个数据集文件



---原始邮件---
发件人: "Hailong ***@***.***&gt;
发送时间: 2023年3月30日(周四) 下午5:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TommyGong08/LSTM_Trajectory_Prediction] 请问有没有数据集的文件呢 (Issue #2)




 
你好，data_single_vehicle.csv里面是数据集的文件。需要更多数据的话可以去看一下NGSIM数据集。
